<a href="https://colab.research.google.com/github/ARizalma/river-water-quality-analysis/blob/main/02_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing

## Objective

The objective of this notebook is to clean and prepare the river water quality dataset for exploratory data analysis and visualization.

In [ ]:
#Import the required libraries for data preprocessing.

import pandas as pd
import numpy as np

In [3]:
# Load Dataset

import requests

url = "https://raw.githubusercontent.com/ARizalma/river-water-quality-analysis/main/Data/river-water-quality-data-for-2023.csv"

df = pd.read_csv(url, sep=";")

In [4]:
df.head()

,titik_sampel,lintang_selatan,bujur_timur,jenis_parameter,parameter,baku_mutu,hasil_pengukuran,periode_data,periode_pemantauan,bulan_sampling,nama_sungai,alamat
0,ANK-1,"-6,175882376","106,7286948",Fisika,TDS,1000,164,2023,Periode 1 (Musim Hujan),2,Angke,Jl. Duri Kosambi (Ciledug)
1,ANK-1,"-6,175882376","106,7286948",FIsika,TSS,50,24,2023,Periode 1 (Musim Hujan),2,Angke,Jl. Duri Kosambi (Ciledug)
2,ANK-1,"-6,175882376","106,7286948",Kimia,pH,6-9,"7,56",2023,Periode 1 (Musim Hujan),2,Angke,Jl. Duri Kosambi (Ciledug)
3,ANK-1,"-6,175882376","106,7286948",Kimia,BOD,3,"23,65",2023,Periode 1 (Musim Hujan),2,Angke,Jl. Duri Kosambi (Ciledug)
4,ANK-1,"-6,175882376","106,7286948",Kimia,COD,25,189,2023,Periode 1 (Musim Hujan),2,Angke,Jl. Duri Kosambi (Ciledug)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10911 entries, 0 to 10910
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sampling_point          10911 non-null  object
 1   latitude                10911 non-null  object
 2   longitude               10911 non-null  object
 3   parameter_category      10911 non-null  object
 4   parameter_name          10911 non-null  object
 5   water_quality_standard  10911 non-null  object
 6   measurement_value       10911 non-null  object
 7   year                    10911 non-null  int64
 8   monitoring_period       10911 non-null  object
 9   sampling_month          10911 non-null  int64
 10  river_name              10911 non-null  object
 11  location                10911 non-null  object
dtypes: int64(2), object(10)
memory usage: 1023.0+ KB

In [5]:
df = df.rename(columns={
    'titik_sampel': 'sampling_point',
    'lintang_selatan': 'latitude',
    'bujur_timur': 'longitude',
    'jenis_parameter': 'parameter_category',
    'parameter': 'parameter_name',
    'baku_mutu': 'water_quality_standard',
    'hasil_pengukuran': 'measurement_value',
    'periode_data': 'year',
    'periode_pemantauan': 'monitoring_period',
    'bulan_sampling': 'sampling_month',
    'nama_sungai': 'river_name',
    'alamat': 'location'
})

In [7]:
df.columns

Index(['sampling_point', 'latitude', 'longitude', 'parameter_category',
       'parameter_name', 'water_quality_standard', 'measurement_value', 'year',
       'monitoring_period', 'sampling_month', 'river_name', 'location'],
      dtype='object')

In [8]:
df[['measurement_value',
    'water_quality_standard',
    'latitude',
    'longitude']].sample(20, random_state=55)

      measurement_value water_quality_standard      latitude    longitude
315               0,019                   0,03     -6,118484    106,95644
2205               0,09                   0,06     -6,292639     106,8535
10090             29,39                      3     -6,202778   106,897639
4772            3500000                   5000  -6,161783569  106,7901797
1527              23,81                      3      -6,18375   106,928806
6266             0,0245                  0,005  -6,174388889  106,8520361
46                256,1                   1000  -6,175882376  106,7286948
7077               8,92                      3      -6,31101   106,807974
8326               0,02                  0,002  -6,261816857  106,8258936
10708             7,925                    6-9  -6,239885363  106,8806538
10425              0,02                   0,03     -6,118972    106,89625
9559                 16                     50     -6,196917   106,746111
4755                120                     25  -6,161783569  106,7901797
6848                 37                     25     -6,229823    106,89098
1491             0,0059                   0,01     -6,188306   106,933917
9847             0,0059                   0,01     -6,284368   106,908756
6866             300000                   1000     -6,229823    106,89098
4933            2400000                   5000     -6,248469   106,932627
4866              177,3                   1000     -6,248469   106,932627
5651               9,05                      3  -6,353515176   106,859912

## Clean Decimal Separator
Convert decimal separators from commas to periods for numerical processing.

In [9]:
# Replace comma decimal separators with periods

df['measurement_value'] = (
    df['measurement_value']
    .astype(str)
    .str.replace(',', '.', regex=False)
)

df['latitude'] = (
    df['latitude']
    .astype(str)
    .str.replace(',', '.', regex=False)
)

df['longitude'] = (
    df['longitude']
    .astype(str)
    .str.replace(',', '.', regex=False)
)

In [10]:
df[['measurement_value', 'latitude', 'longitude']].head()

  measurement_value      latitude    longitude
0               164  -6.175882376  106.7286948
1                24  -6.175882376  106.7286948
2              7.56  -6.175882376  106.7286948
3             23.65  -6.175882376  106.7286948
4               189  -6.175882376  106.7286948

##Convert Data Types
Convert cleaned numerical columns into numeric data types.

In [11]:
# Convert columns to numeric data types

df['measurement_value'] = pd.to_numeric(
    df['measurement_value'],
    errors='coerce'
)

df['latitude'] = pd.to_numeric(
    df['latitude'],
    errors='coerce'
)

df['longitude'] = pd.to_numeric(
    df['longitude'],
    errors='coerce'
)

In [12]:
df[['measurement_value',
    'latitude',
    'longitude']].dtypes

measurement_value    float64
latitude             float64
longitude            float64
dtype: object

## Fix Inconsistent Categories

Standardize inconsistent category labels.

In [13]:
# Standardize category labels

df['parameter_category'] = (
    df['parameter_category']
    .replace({
        'FIsika': 'Fisika'
    })
)

In [15]:
df['parameter_category'].value_counts()

parameter_category
Kimia      9006
Fisika      959
Biologi     946
Name: count, dtype: int64

## Validate Cleaned Dataset

Validate the dataset after preprocessing.

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10911 entries, 0 to 10910
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sampling_point          10911 non-null  object
 1   latitude                10911 non-null  float64
 2   longitude               10911 non-null  float64
 3   parameter_category      10911 non-null  object
 4   parameter_name          10911 non-null  object
 5   water_quality_standard  10911 non-null  object
 6   measurement_value       10911 non-null  float64
 7   year                    10911 non-null  int64
 8   monitoring_period       10911 non-null  object
 9   sampling_month          10911 non-null  int64
 10  river_name              10911 non-null  object
 11  location                10911 non-null  object
dtypes: float64(3), int64(2), object(7)
memory usage: 1023.0+ KB

In [17]:
df.isnull().sum()

sampling_point            0
latitude                  0
longitude                 0
parameter_category        0
parameter_name            0
water_quality_standard    0
measurement_value         0
year                      0
monitoring_period         0
sampling_month            0
river_name                0
location                  0
dtype: int64

In [18]:
df.sample(10, random_state=55)

,sampling_point,latitude,longitude,parameter_category,parameter_name,water_quality_standard,measurement_value,year,monitoring_period,sampling_month,river_name,location
315,BLC-1,-6.118484,106.956440,Kimia,Pb,"0,03",1.900000e-02,2023,Periode 2 (Musim Peralihan),5,Blencong,Jl. Rorotan Marunda
2205,CLW1-3,-6.292639,106.853500,Kimia,Nitrit,"0,06",9.000000e-02,2023,Periode 1 (Musim Hujan),2,Ciliwung,Kampung Gedong (Intake PAM)
10090,STR-4,-6.202778,106.897639,Kimia,BOD,3,2.939000e+01,2023,Periode 4 (Musim Peralihan),9,Sunter,Jl. Jatinegara Kaum
4772,GRL-5,-6.161784,106.790180,Biologi,Total Coliform,5000,3.500000e+06,2023,Periode 4 (Musim Peralihan),9,Grogol,RS Jiwa Grogol Jelambar
1527,CKG-3,-6.183750,106.928806,Kimia,BOD,3,2.381000e+01,2023,Periode 1 (Musim Hujan),2,Cakung,Jl. Raya Bekasi (United Traktor)
6266,KLT-7,-6.174389,106.852036,Kimia,Fenol,"0,005",2.450000e-02,2023,Periode 1 (Musim Hujan),2,Kalibaru Timur,Galur
46,ANK-1,-6.175882,106.728695,Fisika,TDS,1000,2.561000e+02,2023,Periode 3 (Musim Kemarau),8,Angke,Jl. Duri Kosambi (Ciledug)
7077,KRT-1,-6.311010,106.807974,Kimia,BOD,3,8.920000e+00,2023,Periode 1 (Musim Hujan),2,Krukut,Jl. Raya Pondok LABU
8326,MPG-4,-6.261817,106.825894,Kimia,H2S,"0,002",2.000000e-02,2023,Periode 3 (Musim Kemarau),8,Mampang,Jl. Kemang Timur V
10708,TRB-3,-6.239885,106.880654,Kimia,pH,6-9,7.925000e+00,2023,Periode 2 (Musim Peralihan),5,Tarum Barat,Jl. Kalimalang (Jembatan Serong)

## Save Clean Dataset

Save the cleaned dataset for further analysis.

In [19]:
df.to_csv(
    'river-water-quality-data-clean.csv',
    index=False
)

In [21]:
df.describe()

           latitude     longitude  measurement_value     year  sampling_month
count  10911.000000  10911.000000       1.091100e+04  10911.0    10911.000000
mean      -6.215556    106.836691       7.358853e+05   2023.0        6.011823
std        0.064130      0.064713       8.163304e+06      0.0        2.752708
min       -6.370171    106.683389       0.000000e+00   2023.0        2.000000
25%       -6.258022    106.791944       9.000000e-03   2023.0        2.000000
50%       -6.210370    106.836847       3.500000e-01   2023.0        8.000000
75%       -6.161889    106.880654       9.000000e+00   2023.0        9.000000
max       -6.098833    106.969556       3.500000e+08   2023.0        9.000000

## Extreme Measurement Values

In [22]:
df.nlargest(10, 'measurement_value')[
    [
        'parameter_name',
        'measurement_value',
        'river_name',
        'sampling_month'
    ]
]

      parameter_name  measurement_value      river_name  sampling_month
4634  Total Coliform        350000000.0          Grogol               5
4542  Total Coliform        300000000.0          Grogol               5
4543  Fecal Coliform        280000000.0          Grogol               5
4635  Fecal Coliform        280000000.0          Grogol               5
8429  Total Coliform        280000000.0         Mampang               8
8430  Fecal Coliform        280000000.0         Mampang               8
4749  Total Coliform        170000000.0          Grogol               8
8521  Total Coliform        110000000.0         Mampang               8
8522  Fecal Coliform        110000000.0         Mampang               8
5462  Total Coliform         90000000.0  Kalibaru Barat               5

## Preprocessing Summary

### Actions Performed

- Renamed columns to English.
- Standardized decimal separators.
- Converted numerical columns to numeric data types.
- Corrected inconsistent category labels.
- Validated the cleaned dataset.
- Saved the cleaned dataset for further analysis.